### ISSUE TITLE
Unable to define ACL on Resource view

### ISSUE THREAD

**Issue by dfee** [Cornices/cornice#100]
You're unable to specify an acl on a @view decorator for a resource. Here is an example:

```
@resource(path='/api/users/{username}')
class UserResource(object):
    def __init__(self, request):
        self.request = request

    def auth_user(self, request):
        # not called
        return True

    @view(acl=auth_user)
    def get(self):
        # expect to have acl already called; not true
```

This 'acl' actually gets attached when the resource is instantiated (wrapped) in cornice/resource.py:65. However, it never gets called.

**Comment by DaineDanielson** [comment]
@sbbowers suggestion `acl=lambda self:UserResource.__acl__` still looks like the best approach. Please, cornice resources should use Pyramid's built-in `__acl__` magic by default! I'm new to the community, but my 2¢.
