### ISSUE TITLE
Documentation should include working examples for each feature

### ISSUE THREAD

**Issue by sudomake** [Cornices/cornice#101]
It would be really helpful if we had examples that could be copy-paste-run to see how each feature is meant to be used, from both a service and resource approach.

Documentation that confuses me:
____________________________

<pre>
Doing validation and filtering at class level

If you want to use class methods to do validation, you can do so by passing the klass parameter to the hook_view or @method decorators, plus a string representing the name of the method you want to invoke on validation. This means something like this:

class MyClass:
    def validate_it(request):
        # put the validation logic here

@service.get(klass=MyClass, validators=('validate_it',))
def view(request):
    # do something with the request
</pre>

How does the validation work in the method validate_it?  Do I just add errors to the request?  What gets returned (if anything)?  If I try to fill in the blanks and run it I get:
<pre>
File "/local/lib/python2.7/site-packages/cornice/service.py", line 320, in wrapper
    ob = args['klass'](request)
TypeError: this constructor takes no arguments
</pre>

If I add an __init__ method the request never makes it back to my view.  Is this a bug in Cornice or am I not using klass correctly?

Another Example:
_______________
<pre>
Managing ACLs

You can also specify a way to deal with ACLs: pass in a function that takes a request and returns an ACL, and that ACL will be applied to all views in the service:

foo = Service(name='foo', path='/foo', acl=_check_acls)
</pre>

What goes in _check_acls?  What would be an acceptable ACE?  How do I tie an ACE to an http method?  What if I'm using resources instead of services?

A working example for each feature documented, no matter how simple, would help.

**Comment by leplatrem** [comment]
I added some more examples in #397 

Do not hesitate to open a pull-request if you think it's not enough ;) Thanks!
