### ISSUE TITLE
Debugging is difficult

### ISSUE THREAD

**Issue by tdavis** [Cornices/cornice#140]
Debugging errors in Cornice services is rather difficult, owing to the fact that the library doesn't handle exceptions very gracefully. Here are a couple examples:
- `cornice/pyramidhook.py:103` - On `TypeError`, we call `_filter()` again assuming the `request` is culprit. However, if `response` if already an exception, the call fails and swallows the existing stack trace.
- `cornice/cors.py:93` - We simply assume the response is a `Response`, and most exceptions don't have a `headers` attribute; result is same as above. The ones that _do_ make this even more interesting ;)

In both cases, unless `debug_all` is set for Pyramid, whatever caused the original exception is lost entirely. If the flag is set, it will show just the exception message above the useless stack trace, leaving the user to figure out what the original stack trace was.

I would fix this myself but I can't immediately tell how these exceptions are getting further along the response pipeline in the first place, as `Service.decorate_view()` doesn't actually trap anything.

**Comment by leplatrem** [comment]
I think this was fixed. Please re-open if I'm wrong!
