### ISSUE TITLE
When sphinx docgenerator is invoked multiple times, the service docs are duplicated

### ISSUE THREAD

**Issue by bpielech** [Cornices/cornice#148]
I have 4 services that I'd like to document, but when I document them with separate section headers as follows:

A
------
.. services::
   :modules: service.a

B
-------------
.. services::
   :modules: service.b

C
------------
.. services::
   :modules: service.c

D
----
.. services::
   :modules: service.d

the generated doc ends up with the documentation for prior services duplicated each time:

A
AB
ABC
ABCD 

but if I document it as:

.. services::
   :modules: service.a, service.b, service.c, service.d

the docs are generated as expected. 

It seems that sphinxext does not clean up the list of services after it is done generating docs.

**Comment by leplatrem** [comment]
We're moving the ext out the Cornice repo. Please reopen the issue in https://github.com/Cornices/cornice.ext.sphinx if still relevant ;)
