### ISSUE TITLE
ConfigurationConflictError when using a manually-committing Configurator

### ISSUE THREAD

**Issue by abrookins** [Cornices/cornice#151]
When using 0.14 in a Pyramid project, I get a ConfigurationConflictError on trying to run `pserve` that appears to arise because a Cornice resource with e.g. get() and put() methods results in multiple calls to `Configurator.add_view` with the same name.

Here's a traceback I made while writing a test to exercise the bug:

```
Traceback (most recent call last):
  File "/Users/andrew/src/cornice/cornice/tests/test_resource.py", line 101, in setUp
    self.app = TestApp(CatchErrors(self.config.make_wsgi_app()))
  File "/Users/andrew/envs/cornice/lib/python2.7/site-packages/pyramid-1.4.2-py2.7.egg/pyramid/config/__init__.py", line 956, in make_wsgi_app
    self.commit()
  File "/Users/andrew/envs/cornice/lib/python2.7/site-packages/pyramid-1.4.2-py2.7.egg/pyramid/config/__init__.py", line 630, in commit
    self.action_state.execute_actions(introspector=self.introspector)
  File "/Users/andrew/envs/cornice/lib/python2.7/site-packages/pyramid-1.4.2-py2.7.egg/pyramid/config/__init__.py", line 1065, in execute_actions
    for action in resolveConflicts(self.actions):
  File "/Users/andrew/envs/cornice/lib/python2.7/site-packages/pyramid-1.4.2-py2.7.egg/pyramid/config/__init__.py", line 1193, in resolveConflicts
    raise ConfigurationConflictError(conflicts)
ConfigurationConflictError: Conflicting configuration actions
  For: ('view', None, '', 'user', 'a9204cf84fd843dac4e2dad4c4b72fed')
    Line 76 of file /Users/andrew/src/cornice/cornice/resource.py:
        config.add_cornice_service(service)
    Line 76 of file /Users/andrew/src/cornice/cornice/resource.py:
        config.add_cornice_service(service)
  For: ('view', None, '', 'user', 'b1b988966518e8d3f972d463b864549f')
    Line 76 of file /Users/andrew/src/cornice/cornice/resource.py:
        config.add_cornice_service(service)
    Line 76 of file /Users/andrew/src/cornice/cornice/resource.py:
        config.add_cornice_service(service)
```

I fixed this by calling `Configurator.commit` in the two places in `pyramidhook.register_service_views` where the code calls `Configurator.add_view`, which is one way the Pyramid docs suggest of handling this issue (http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/advconfig.html#using-config-commit).

**Comment by mmerickel** [comment]
> After looking more closely at the issue, the error seems correct. Shouldn't adding two view decorators without any custom predicates or anything raise that error? But if a project is auto-committing changes, then Pyramid turns off conflict detection, and I presume the last view added is always used.

The **required** commits in cornice absolutely indicate an issue. No library should ever perform a commit as it means that the user cannot safely override those actions. The `ConfigurationConflictError` was emitting a real error, and performing the commit merely hides it by allowing the last view to win.
