### ISSUE TITLE
Quickstart Documentation Incomplete

### ISSUE THREAD

**Issue by gewthen** [Cornices/cornice#168]
The documentation does not specify that "config.include("cornice")" must be added to the __init__.py file in order to use cornice. Not everyone will be starting from an new empty project. It would have been nice to be been told this in the quickstart, rather than having to look at an example project.

**Comment by tisdall** [comment]
Okay, I just encountered this...  almost 2 yrs after this was reported.  I figured it out by creating the paster template and then looking at the code generated, but that shouldn't be necessary.

**Comment by ametaireau** [comment]
Does the pull request look okay to you? Please, don't hesitate to create pull requests for documentation or code changes, I would gladly merge them if they're useful!

**Comment by tisdall** [comment]
Yeah, I was thinking about making a PR, but I wasn't really sure where all to put it (I'm just getting to know the project).  #305 looks good, but you should also add something similar to tutorial.rst since it also mentions starting with generating a paster template.

**Comment by leplatrem** [comment]
Was done in #305, please submit a pull-request if the current docs are not clear enough ;)
