### ISSUE TITLE
support for flattened schema in querystring

### ISSUE THREAD

**Issue by matleh** [Cornices/cornice#173]
The API I am workin on needs query-parameters like `?x.a=123&x.b=456`. Colander has the unflatten method for these use-cases, but I can not see, how I can make use of that when using Cornice.

It looks like `validate_colander_schema` needs code to explicitly support that use-case. I could try to work on that, if there are no other existing ways to achieve that - maybe using some clever colander tricks, like preparer or defered-fields.

Did anybody have a similiar use-case before? What are your opinions on this?

**Comment by leplatrem** [comment]
This should be fixed with the new API in Cornice 2.0 (current master) :)
