### ISSUE TITLE
Cornice skips the `preparer` and `validator` steps of a SchemaNode subclass

### ISSUE THREAD

**Issue by abourget** [Cornices/cornice#190]
Having something like this:

    class TransactionsPostSchema(SchemaNode):
        def preparer(self, value):
            value = merge_src_token_with_src_account(value)
            return value

        def validator(self, node, value):
            .. do stuff ..

        src_account = SchemaNode(String(), missing=None)
        src_token = SchemaNode(String(), missing=None)
        dst_account = SchemaNode(String())

When using with:

    @my_service.post(schema=TransactionsPostSchema)
    def my_service_post(request):
        ....

Cornice disregards the `preparer` and `validator` at this level, because it loops on the `.children` of the root node only.  It would need to either re-apply manually the calls to the `preparer` (that we find in colander's `_SchemaNode::deserialize` function) and `validator`.  That wouldn't be very DRY though.

The other option might be to instead call .deserialize() on the root Schema after checking that the attributes are "present" at the correct location. This way, colander would do the job it does normally.

So what I understand, is that the passed-in Schema is only used as a "container" for its children.  In that case, how would I achieve what I'm trying to do here, without passing "validators=my_prepare_and_validators" on each service view config ?

As a side note, shouldn't it be documented that the `location` element is only verified on the first level ? On the immediate children of the root schema passed in the view configurator.  It wasn't clear to me where the `location` should be, or even if it was required at all.

**Comment by alexsv** [comment]
+1

**Comment by delijati** [comment]
+1

**Comment by leplatrem** [comment]
This will be solved in Cornice 2.0 (c.f. current master)
