### ISSUE TITLE
Colander validation breaks on invalid JSON input data

### ISSUE THREAD

**Issue by amarandon** [Cornices/cornice#201]
Probably a side effect of my work on deserializers:

    $ curl -H 'Accept: application/json' -H 'Content-Type: application/json' http://0.0.0.0:6543 -d 'blah'

Triggers an exception:
```
  File [...]/cornice/schemas.py", line 108, in validate_colander_schema
    qs, headers, body, path = extract_request_data(request)
  File [...]/cornice/util.py", line 116, in extract_request_data
    body = deserializer(request)
  File [...]/cornice/util.py", line 95, in extract_json_data
    return body
UnboundLocalError: local variable 'body' referenced before assignment
```

I'll look into it.

**Comment by leplatrem** [comment]
Closing since we made big refactor of the API... 

Please reopen if still exists and relevant on current master! Thanks!
