### ISSUE TITLE
need a way to trap unknown keys in 'querystring' of colander schema

### ISSUE THREAD

**Issue by joesteeve** [Cornices/cornice#211]
Cornice silently ignores keys that are not found in a colander schema. This is not favourable with the 'querystring' location. Unknown keys in the 'querystring' is an error. There should be a way to specify this in the schema so that cornice can report the error to the client.

**Comment by leplatrem** [comment]
With the new approach in Cornice 2.0 (current master), this will be possible via Colander (cf. `unknown='raise'`: http://docs.pylonsproject.org/projects/colander/en/latest/api.html?highlight=missing#types)
