### ISSUE TITLE
invalid option name in cornice.ext.sphinxext

### ISSUE THREAD

**Issue by machinist** [Cornices/cornice#231]
73         # filter the services according to the options we got
 74         services = get_services(names=names or None,
 75                                 exclude=self.options.get('exclude'))

line 75: i believe the option is actually called ignore

**Comment by leplatrem** [comment]
We're moving the ext out the Cornice repo. Please reopen the issue in https://github.com/Cornices/cornice.ext.sphinx if still relevant ;)
