### ISSUE TITLE
Schema validation may throw an uncaught exception with valid JSON

### ISSUE THREAD

**Issue by ltvolks** [Cornices/cornice#249]
A service validating with a colander schema requires that the request body deserialize to a dictionary. 

If the JSON body deserializes to anything else, an uncaught exception will be thrown. The example below demonstrates the behavior. There we attempt to post JSON with a top-level Array (valid per spec), and a colander exception bubbles up.

It doesn't matter what type of validation schema is defined since the cornice behaviors [here](https://github.com/mozilla-services/cornice/blob/master/cornice/schemas.py#L98) and [here](https://github.com/mozilla-services/cornice/blob/master/cornice/schemas.py#L150) rely on the schema being a `colander.Mapping` type. (I thought a `colander.SequenceSchema` should work as a validator but that is another issue),

```python
import colander
from cornice.service import Service
from pyramid.config import Configurator
from webtest import TestApp


class ValidationSchema(colander.MappingSchema):
    key = colander.SchemaNode(colander.String())

svc = Service(name="test", path="/test")
svc_validation = Service(name="test-validation", path="/test-validation")


@svc.post()
def post(request):
    return {"test": "succeeded"}


@svc_validation.post(schema=ValidationSchema)
def post(request):
    return {"test": "succeeded"}


config = Configurator()
config.include("cornice")
config.scan()
app = config.make_wsgi_app()

client = TestApp(app)

# no validation performed...the deserialized list is available to the view
client.post_json('/test', [1, 2, 3])

# Throws an exception
client.post_json('/test-validation', [1, 2, 3])
```

Traceback:
```python
  File "/venvs/cornice-test/src/cornice/cornice/service.py", line 495, in wrapper
    validate_colander_schema(args['schema'], request)
  File "/venvs/cornice-test/src/cornice/cornice/schemas.py", line 147, in validate_colander_schema
    _validate_fields('body', body)
  File "/venvs/cornice-test/src/cornice/cornice/schemas.py", line 99, in _validate_fields
    data = webob.multidict.MultiDict(schema.unflatten(data))
  File "/venvs/cornice-test/src/cornice/cornice/schemas.py", line 81, in unflatten
    return self.colander_schema.unflatten(data)
  File "/venvs/cornice-test/lib/python2.7/site-packages/colander/__init__.py", line 1880, in unflatten
    paths = sorted(fstruct.keys())
AttributeError: 'list' object has no attribute 'keys'
```

A custom deserializer can be registered for a quick fix. This will ensure that the returned body is a dictionary (with a bogus key). Validation can proceed (and fail), but no exception is thrown.

```python
from collections import Mapping
# No error handling!
def custom_deserializer(request):
    body = json.loads(request.body)
    if not isinstance(body, Mapping):
        body = {'__cornice_dummy__': body}
    return body
```

**Comment by leplatrem** [comment]
We completely refactored (and removed) the code that was at the origin of this stack. I'm closing this issue for now, please reopen if you can reproduce on Cornice 2.0 (current master). Thanks!
