### ISSUE TITLE
Defining schema dynamically with schema attribute need to be able say that you don't actually want to use a schema

### ISSUE THREAD

**Issue by lieryan** [Cornices/cornice#251]
The doc mentioned using [schema() property](http://cornice.readthedocs.org/en/latest/validation.html#schema-validation) on a resource class to use dynamic schema:

```python
@property
def schema(self):
    if should_use_schema(self.request):
        return CorniceSchema(...)
    # don't want to use schema, returning None doesn't work...
```

however, this breaks when I want to use schema only for a certain condition but use the regular no-schema behavior otherwise. 

A workaround is to create a Fake Schema class and return that:

```python
class FakeSchema(object):
    def get_attributes(self, *args, **kwargs):
        return []
@property
def schema(self):
    if should_use_schema(self.request):
        return CorniceSchema(...)
    return FakeSchema()
```

If you're on Python 2.x, you can also workaround this by raising any Exception, but this workaround depends on the exception-swallowing behavior of `hasattr()` that has [changed in Python 3](https://mail.python.org/pipermail/python-3000/2008-January/011771.html):

```python
@property
def schema(self):
    if should_use_schema(self.request):
        return CorniceSchema(...)
    raise Exception()
```

**Comment by Zatsugami** [comment]
It could be possibly easy to achieve.

```python
def validate_colander_schema(schema, request):
    """Validates that the request is conform to the given schema"""


    if schema is None:
        # Just do not validate anything if no schema was supplied, maybe issue a log.warn ?
        return


    from colander import Invalid, Sequence, drop, null, MappingSchema

    schema_type = schema.colander_schema.schema_type()
    unknown = getattr(schema_type, 'unknown', None)
```

**Comment by leplatrem** [comment]
We reworked the whole schema API in Cornice 2.0 (current master), and this shouldn't be relevant anymore, now that we make everything explicit
