### ISSUE TITLE
Rebuilding sphinxext-powered docs.

### ISSUE THREAD

**Issue by myroslav** [Cornices/cornice#258]
After one changes documentation in cornice docstrings, and rebuilds the documentation, the page that `services` reStructuredText directive is used on is not regenerated unless one does the change to the page itself.

Locally workaround as simple as `touch docs/source/api.rst` works, but this becomes highly inconvenient for code that is in github and documentation auto-generated on RTD, since I need to simulate actual change to the file to make that change trigger page rebuild on RTD.

It would be great to have `sphinxext` influence the decision of Shinx to rebuild page, or there can be some way to force the page rebuild for sphinxext-powered pages. Is there any?

**Comment by leplatrem** [comment]
We're moving the ext out the Cornice repo. Please reopen the issue in https://github.com/Cornices/cornice.ext.sphinx if still relevant and useful for you ;)
