### ISSUE TITLE
Pyramid views defined inside cornice resources no longer work

### ISSUE THREAD

**Issue by rdrey** [Cornices/cornice#265]
When defining a pyramid view 'manually' (with `@view_config`) inside a service object annotated with `@resource`, pyramid's `scan()` can no longer find the view.

This used to work in pyramid==1.5, but no longer works as of pyramid>=1.5.1

**Comment by leplatrem** [comment]
I'm closing the issue, feel free to reopen if you really think there's something we can do about that
