### ISSUE TITLE
addition of `type` attribute on colander elements

### ISSUE THREAD

**Issue by tisdall** [Cornices/cornice#310]
Colander elements already have colander types, but the examples in Cornice and the tests seem to have added another attribute called `type`.  The code indicates that if you don't add this new `type` it just uses the colander `typ` instead.  What is the purpose of this new `type` attribute?

**Comment by delijati** [comment]
+1

**Comment by leplatrem** [comment]
This was fixed in Cornice 2.0 (current master)
