### ISSUE TITLE
Colander missing=drop + Sphinx (via cornice-autodoc) result in 'not JSON serializable' while building docs

### ISSUE THREAD

**Issue by evgenyz** [Cornices/cornice#315]
When building docs with Sphinx I got:

```
Exception occurred:
  File "/usr/lib64/python3.4/json/encoder.py", line 173, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <colander._drop object at 0x7f1cfc41ceb8> is not JSON serializable
```

The problem part is *missing=drop* declaration.

```python
   title = SchemaNode(
        String(),
        location="body",
        type='non-empty string',
        missing=drop)
```

And if you change it to missing=None, problem goes away.

Everything is current from pip (in virtualenv), Python 3.4

**Comment by tisdall** [comment]
Can you provide your whole schema?  `missing=colander.drop` only works on elements that are children of a `MappingSchema`.

**Comment by evgenyz** [comment]
It's just as simple as

```
class BrowseFiltersSchema(MappingSchema):
   title = SchemaNode(
      String(),
      location="body",
      type='non-empty string',
      missing=drop)
```

**Comment by ametaireau** [comment]
Oh that's interesting. I don't know why this is happening and was working before. Did colander changed something in their implem? Is it a python 3k only problem?

I would be happy to fix this in the documentation. If you want you can submit a pull request and I will happily merge it. Otherwise I can just fix it

**Comment by evgenyz** [comment]
Actually, I don't really know what is the exact underlying problem that causes such a behavior (nor I have any patch). But I'll gladly provide support in fixing this for anyone who have ideas about where to dig.

**Comment by tisdall** [comment]
I'm wondering if this is related to #317

**Comment by evgenyz** [comment]
I've applied patch from #317 manually. Still no difference (it seems that this code path is not used in the docs generation process at all).

**Comment by tisdall** [comment]
@evgenyz - I wasn't suggesting using that patch... only that it may be related.  #317 seems to fail some tests so I'm not even sure it fixes what it's mentioning.

**Comment by leplatrem** [comment]
We're moving the ext out the Cornice repo. Please reopen the issue in https://github.com/Cornices/cornice.ext.sphinx if still relevant and useful for your use case ;)
