### ISSUE TITLE
CORS support fails with credentials & All origin allowing

### ISSUE THREAD

**Issue by treerao** [Cornices/cornice#319]
I'm encountering a problem with the CORS support when using credentials.  In particular, I get the following error in latest Chrome, latest Cornice:

> XMLHttpRequest cannot load '....' A wildcard '*' cannot be used in the 'Access-Control- Allow-Origin' header when the credentials flag is true. Origin '....' is therefore not allowed access.

What I think should be happening is the server should be setting the 'Access-Control-Allow-Origin' response header to the origin provided in the credentialed request.

Looking at the source, first I notice that line [cors.py:100](https://github.com/mozilla-services/cornice/blob/master/cornice/cors.py#L100) is checking for a header on the request, Access-Control-Allow-Credentials, which i believe is meant to be a response header.  If instead the test checked the service for credentials support as it does on [cors.py:124](https://github.com/mozilla-services/cornice/blob/master/cornice/cors.py#L124), then the action I would want would happen here as apparently intended.  Alternatively this Access-Control-Allow-Origin can be set right there in the then of that test to the origin.

**Comment by ametaireau** [comment]
Hi!

Thanks for reporting the issue. It seems pretty straightforward to fix. Would you like to work on a fix?

**Comment by treerao** [comment]
Sure, submitted a pull request now.

**Comment by leplatrem** [comment]
As far as I understand, this was merged :)
