### ISSUE TITLE
Code in resource decorator that never gets executed

### ISSUE THREAD

**Issue by mamalos** [Cornices/cornice#321]
The condition in file resource.py line 45 almost never returns True, and in practice it never gets executed.

Excerpt (lines 44, 45):

if prefix == 'collection_' and service_args.get('collection_acl'):
                service_args['acl'] = service_args['collection_acl']

Based on the code of lines 33-42 of the same file, the only way the aforementioned condiction would return True, would be if a given keyword-argument has the exact form: collection_collection_acl 

which is not an option.

**Comment by tisdall** [comment]
According to the coverage report from nose there's no test case covering that.  In the current repo it's line 50 .

**Comment by leplatrem** [comment]
Thanks for this! You were right!

Fixed in #417
