### ISSUE TITLE
Cornice CORS doesn't seem to work for resources

### ISSUE THREAD

**Issue by yourslab** [Cornices/cornice#332]
I've set the following parameters for my resources:

```
@view(http_cache=0, renderer='string', cors_origins=('*',), cors_headers=('*',), cors_enabled=True)
def get(self):
    // Filler code
```

I've also tried enabling CORS on the resource itself:

```
@resource(collection_path='...', path='...', cors_origins=('*',), cors_headers=('*',), cors_enabled=True)
```

However, whenever I try to request the respective URL from any web browser, I always get the following error:

```
XMLHttpRequest cannot load http://localhost:6543/(...). Origin (...) is not allowed by Access-Control-Allow-Origin.
```

**Comment by leplatrem** [comment]
From what I read here: https://github.com/mozilla-services/cornice/blob/master/cornice/resource.py#L75-L82 it should work :(

Did you try to dig in about the service arguments ?

As a workaround you can also set CORS globally on the Service class directly...
Example: https://github.com/mozilla-services/cliquet/blob/2.5.0/cliquet/__init__.py#L127-L129

**Comment by ametaireau** [comment]
In order to debug what is happening, you can do an `OPTION` request and see what the server answers.

**Comment by tsauerwein** [comment]
We are setting the CORS configuration on `@resource` and this works for us:

    cors_policy = dict(
        headers=('Content-Type'),
        origins=('*')
    )

    @resource(collection_path='...', path='.../{id}',
             cors_policy=cors_policy)
    class MyResource(object):
