### ISSUE TITLE
Sphinx literalinclude, include not working

### ISSUE THREAD

**Issue by amng** [Cornices/cornice#360]
Hi,

I was trying to get the include directives of sphinx to work when documenting the api, in order to show some examples of possible responses without putting all those responses in the code.

        """
        Some resource

        .. literalinclude:: response.json
           :language: json
           :linenos:
        """

However when I try to put that directive, I cannot generate the documentation due to the following error:

    Exception occurred:
      File ".../site-packages/sphinx/directives/code.py", line 198, in run
        if not document.settings.file_insertion_enabled:
    AttributeError: Values instance has no attribute 'file_insertion_enabled'
    The full traceback has been saved in /tmp/sphinx-err-zenmNc.log, if you want to report the issue to     the developers.
    Please also report this if it was a user error, so that a better error message can be provided next  time.
    A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

I tried using the same directive on sphinx outside the cornice-autodoc directive and it works as expected.
Not sure if this is the expected behavior for cornice or not, but since for example the image directive works as expected I was hoping the include would also work.

Thanks in advance

**Comment by amng** [comment]
For now I've found a quick fix for the include directive though the literalinclude is still not working.
In the file **.../site-packages/cornice/ext/sphinxext.py** I changed:
```python
def rst2node(data):
    ...
    document.settings.rfc_references = False
    document.settings.file_insertion_enabled = True # added line
    ...
```

```python
class Env(object):
    temp_data = {}
    docname = ''

    def relfn2path(self, filename, docname=None):   # added line
        return filename, "source/" + filename       # added line
```

Note that I used the source dir because that's the dir I'm using as relative to the files I'm going to use include.

With these two changes I was able to use the include directive like:

```python
.. include:: files/example_file.rst
```

For the literalinclude I now get the following error:
```ShellSession
Exception occurred:
  File ".../site-packages/sphinx/directives/code.py", line 220, in run
    encoding = self.options.get('encoding', env.config.source_encoding)
AttributeError: 'Env' object has no attribute 'config'
The full traceback has been saved in /tmp/sphinx-err-Lqq5Xc.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 1
```

**Comment by leplatrem** [comment]
We're moving the ext out the Cornice repo. Please reopen the issue in https://github.com/Cornices/cornice.ext.sphinx if you still have the use-case and if it still exists!
Your use-case seems a bit specific, submitting a pull-request would be the best strategy to get this fixed :| Thanks!
