### ISSUE TITLE
Docs: fix validation example

### ISSUE THREAD

**Issue by mjmare** [Cornices/cornice#363]
In the section http://cornice.readthedocs.io/en/latest/validation.html#doing-validation-and-filtering-at-class-level the validation method should have a different signature:

def validate_it(request):
should be 
def validate_it(self, request):

Furthermore it would be useful to know if the order in which validators are applied is guaranteed, eg first schema validation, then the provided validators in order.

**Comment by leplatrem** [comment]
Fixed in current master
