### ISSUE TITLE
switch to cookiecutter

### ISSUE THREAD

**Issue by mmerickel** [Cornices/cornice#388]
Hey folks, we're well on our way to deprecating pcreate [1] in pyramid 1.8 and switching all of our default scaffolds over to using cookiecutter [2][3]. I wanted to give a heads up incase it helps. It's only a deprecation right now with no removal until at least pyramid 1.10.

[1] https://github.com/Pylons/pyramid/issues/2384
[2] https://github.com/Pylons/pyramid-cookiecutter-starter
[3] https://github.com/audreyr/cookiecutter

**Comment by leplatrem** [comment]
Thanks for the heads up! 

We'll get rid of the scaffhold in this repo, and create a cookiecutter template in a separate repo in the Cornices org.
