### ISSUE TITLE
Upgrading docs link results in 404

### ISSUE THREAD

**Issue by bomb-on** [Cornices/cornice#405]
Link in release description (https://github.com/Cornices/cornice/releases/tag/2.0.0) for info about upgrading (https://cornice.readthedocs.io/en/stable/upgrading.html) results in "`SORRY, This page does not exist yet.`" message. Also, seems like the markup for the same link is not quite correct since the link does not render out properly.
I managed to find the upgrading page on this link tho ->  http://cornice.readthedocs.io/en/latest/upgrading.html

**Comment by leplatrem** [comment]
Thanks for the feedback! I fixed it I think.

It's strange though: from the readthedocs interface the tag behind the *stable* docs is `2.0.1`...
