### ISSUE TITLE
add error code in error outputs 

### ISSUE THREAD

**Issue by tarekziade** [Cornices/cornice#41]
23:48 < tarek> we can add a list of them in cornice for sure, 
23:48 < tarek> stuff like 'invalid json' is something that would be better of an error code
23:48 <@mconnor> tarek: mostly it's "if I get HTTP 400, with error 6, it should always be 'JSON parse failure' and not some other state"

**Comment by leplatrem** [comment]
This is 4 years old and never happened. Closing.
