### ISSUE TITLE
Do you plan on dropping indefinitely SPORE ?

### ISSUE THREAD

**Issue by olemoign** [Cornices/cornice#410]
Hi,

I saw that you dropped all ext modules and recreated the sphinx and swagger repos.
Does this mean that SPORE support is definitively dropped ?

Thanks !

**Comment by leplatrem** [comment]
Hi!
Yes, we don't plan to maintain this extension as part of the `cornice` package.
**But**, if you're interested, we can create a repo in the Cornices organization and give you enough permissions to maintain it! That's what we did for the swagger ext. for example.
Let us know!

**Comment by Natim** [comment]
I think we should create the repos with the previous code even if @olemoign doesn't accept the invitation.

**Comment by olemoign** [comment]
Hi. 
To be honest I'm working on a project where a previous dev used Spore but I've never looked into that library so I don't think I would be the right person to do that.

**Comment by leplatrem** [comment]
@Natim go ahead ;)

**Comment by leplatrem** [comment]
Closing, since the question was answered :) Feel free to re-open if you think there's more to discuss :)
