### ISSUE TITLE
Clarify colander_validator behavior when no schema is specified.

### ISSUE THREAD

**Issue by dairiki** [Cornices/cornice#414]
The docstring for ``colander_validator`` states “If no schema is defined, this validator does nothing”, however, currently, an exception is raised if ``schema`` is ``None``.

https://github.com/Cornices/cornice/blob/master/cornice/validators/_colander.py#L47
https://github.com/Cornices/cornice/blob/master/cornice/validators/_colander.py#L63

Which is the desired behavior?

**Comment by leplatrem** [comment]
I'd rather avoid errors at runtime. Maybe make validator useless if no schema, but output some `logger.warn()` instead of raising `TypeError`?

**Comment by dairiki** [comment]
Personally, I'm fine with having ``schema=None`` turn ``colander_validator`` into a silent no-op.  This allows one to include ``colander_validator`` in the default list of validators specified for all services, then set ``schema=None`` on specific services to indicate that no schema validation is to be done.

I don't particularly like doing a ``logger.warn()`` — either it's an error to call ``colander_validator`` with ``schema=None`` or it's not.  Allowing it but cluttering up the log doesn't seem like the right solution to me.  (Issuing a ``warnings.warn()`` warning instead might be a reasonable alternative.)

**Comment by leplatrem** [comment]
I agree with you! Let's keep it simple, silent no-op if no schema.
