### ISSUE TITLE
Allow json body to be a sequence with colander_validator

### ISSUE THREAD

**Issue by gabisurita** [Cornices/cornice#433]
Right now JSON validators just accepts objects as JSON bodies. Is there a reason to not accept Arrays as well?

From https://github.com/Kinto/kinto/issues/880

**Comment by Natim** [comment]
Yes the reason is that you can have security issue if you return an array.

See http://stackoverflow.com/questions/3503102/what-are-top-level-json-arrays-and-why-are-they-a-security-risk

**Comment by leplatrem** [comment]
> you can have security issue if you return an array.

In @gabisurita use-case, she wants to validate an incoming array in the request body (json patch RFC)

**Comment by Natim** [comment]
The security issue is only if the array is at the top level,

**Comment by gabisurita** [comment]
In this case, it is. But it's only on the request. Should we be concerned as well?

**Comment by Natim** [comment]
I guess it is fine on the request.

**Comment by leplatrem** [comment]
The security problem concerns parsing (and instantiate) of arrays in JSON responses on the client side (the browser).
In this case, we want to be able to have request.body validated as array. I don't see any problem with that :)
