### ISSUE TITLE
Controller resources

### ISSUE THREAD

**Issue by cecilphillip** [Cornices/cornice#441]
Is there a recommended way to create controller resources in cornice.

Let's say I have a `/students` resource. In addition to the typical `GET`, `PUT`, `POST`, `DELETE` on that resource I'd like to be able to `POST` to `/students/suspend` for instance. I'm guessing that I could create another cornice `Service` but I was just wondering if there was a better way.

**Comment by Natim** [comment]
Cornice is a rest API, what you are suggesting is not REST compliant.
You should support a PUT on /students/student_id with `suspend: true` to do that.

**Comment by cecilphillip** [comment]
That's understandable.
Thanks for the response.
