### ISSUE TITLE
Python 3, sphinx fails on generating schema validaton text

### ISSUE THREAD

**Issue by stesle** [Cornices/cornice#443]
sphinx-build -a source/ build/
Exception occurred:
  File "/var/lib/pws3/lib64/python3.4/site-packages/cornice_sphinx/__init__.py", line 138, in _render_service
    attributes = schema.get_attributes(location=location)
AttributeError: 'PortraitSchema' object has no attribute 'get_attributes'

**Comment by Natim** [comment]
Hi @stesle which version of Python are you using?
I tried locally here with Python3.5 and the docs build perfectly.

Can you try the following:

```
$ python3 -m venv .venv
$ make docs
```

**Comment by stesle** [comment]
Python 3.4
I tried with a Python 3.5.1 venv. Same error.
The docs build fine as long as there are no schema validators on the service.

Fail:
@portrait.post(validators=check_server,schema=PortraitSchema)
Ok:
@portrait.post(validators=check_server)

**Comment by leplatrem** [comment]
I don't think it comes from the version of Python.

When I read the code here:
https://github.com/Cornices/cornice.ext.sphinx/blob/0.1/cornice_sphinx/__init__.py#L133-L138
I can see that cornice_sphinx is not compatible with Cornice 2.X schemas.

As far as I can tell, the Sphinx extension does not have any active maintainer that could fix this for you. But if you are willing to contribute a fix, we will gladly review it (and release it)!

**Comment by leplatrem** [comment]
Issue opened on dedicated repo: https://github.com/Cornices/cornice.ext.sphinx/issues/10
