### ISSUE TITLE
From Route to cornice.resource.resource and/or cornice.resource.view

### ISSUE THREAD

**Issue by wjehenddher** [Cornices/cornice#450]
Hello,
I'm  trying to deal with ACL per HTTP method on a single `@resource` (See #120, #322).

(roughly)

```python
@resource(name='Items', collection_path='/items', path='/items/{id}')
class ItemsResource(object):

    def __init__(self, request):
        self.request = request

    @view(permission='view')
    def collection_get():
        """GET /items"""
        pass

    @view(permission='add')
    def collection_post():
        """POST /items"""
        pass

    @view(permission='edit')
    def put():
        """PUT /items/{id}"""
        pass

```

The idea is that `ItemsResource` somehow assists the `IAuthenticationPolicy` to return the list of `effective_principals`, taking into consideration the actual resource being accessed (e.g. `/item/{id}`) and `authenticated_userid` in the `request`.

I figured I could do such if I could retrieve the `ItemsResource` instance from `request.context` or from `request.matched_route`.

Is it possible to navigate from `request` to `ItemsResource` anyhow?

(Pyramid 1.5.1 and Cornice 1.0.0 - yes: very old)

**Comment by wjehenddher** [comment]
Perhaps https://github.com/Cornices/cornice/issues/105#issuecomment-255085263?

**Comment by leplatrem** [comment]
The resource is still an obscure and unclear part of the code for me.

From what I read in `resource.py`, there is nothing that attaches the `klass` to the service. I guess this something we can add if you're willing to contribute it.

You would access the resource class with something like `request.current_service.resource_class`, no?

**Comment by wjehenddher** [comment]
Thank you @leplatrem

I've been trying to cope with the ACL per `(resource, request.matched_route)` pair. Hence I thought that getting the instance of `Resource` would help somehow.

The problem is producing `effective_principals` and/or `__acl__` at the correct time so *authentication* and/or *authorization* in pyramid grants/denies access to the `cornice.service._UnboundView`.

I am now trying to leverage pyramid's `root_factory` instance (e.g. `Configurator(settings=..., root_factory="myserver.Root")`), which happens to be `request.context` later on, to see if I can produce ACL dynamically using the `Resource`. Perhaps from `request.context` to `cornice.service.Service|Resource|_UnboundView` would help. Don't know yet.
 
I think that exposing the actual instance of the `cornice.service.Service|Resource` being associated to the current `request.matched_route` would add flexility.

I would be happy to contribute but the main goal for me is to dynamically generate an ACL based on the current `(resource, request.matched_route)` pair.

How can we kick that off?
Especially, getting other contributors better versed in the Authn/Authz side of things to weigh in

**Comment by leplatrem** [comment]
> I think that exposing the actual instance of the cornice.service.Service|Resource being associated to the current request.matched_route would add flexility.

Yes, definitely ! In other projects, we ended-up [implementing it in hacky ways](https://github.com/Kinto/kinto/blob/master/kinto/core/utils.py#L266-L280)

We can start with that if you want :) 

As for getting other contributors, we can ping some Pyramid contribs for some review when we tackle #452

**Comment by wjehenddher** [comment]
Sounds like a plan.

I will continue to explore a viable solution to our Authn/Authz issue (in Cornice 1.0.0) and hopefully devise something useful towards #452.

One other difficulty we face is our production baseline: Pyramid 1.5 and Cornice 1.0.0. Upgrading our baseline to latest releases posts many challenges on our end.

**Comment by leplatrem** [comment]
Cool! 

Don't worry this part hasn't changed much, so we can port it later based on what you achieve from the 1.0 branch

**Comment by wjehenddher** [comment]
Not applicable given that #452 has been pulled.
