### ISSUE TITLE
Raising vs Returning an error response

### ISSUE THREAD

**Issue by jenstroeger** [Cornices/cornice#453]
What is the recommended and safe way to produce an error response?

Often I have code as follows:
```python
    data = get_data_from_db(data_id)
    if data is None:
        request.errors.add("body", "data_id", "Invalid data id")
        request.errors.status = 404 # Not Found
        return
```
which works fine. However, based on [this answer](https://stackoverflow.com/questions/29229348/when-does-pyramid-commit-zodb-transaction#29229427), returning won’t abort the db transaction that is tied to the request. Most of the time that’s not a problem because persistent objects are modified only after all checks have passed.

I would like some clarification here. Is it recommended to `raise HTTPNotFound` here instead of `return`? Are there performance implications of one over the other?

**Comment by leplatrem** [comment]
To be honest, I don't know about performance impact.

In our applications, we raise exceptions and have dedicated error views for specific response rendering (like 404 JSON responses).

As for transactions, pyramid_tm for example, looks at the final response status to decide whether to abort or commit. So I don't think it cares if it was through and exception or a return in a view.

**Comment by jenstroeger** [comment]
> In our applications, we raise exceptions and have dedicated error views for specific response rendering (like 404 JSON responses).

If it’s open source, mind sharing a link to what you would consider a clean and well-formed view implementation? I often find it helpful to learn by reference…

In particular, does Cornice have a “catch all exceptions” view or should I use [Pyramid’s exception context](https://docs.pylonsproject.org/projects/pyramid-cookbook/en/latest/pylons/exceptions.html#exception-views) for that?

> As for transactions, pyramid_tm for example, looks at the final response status to decide whether to abort or commit. So I don't think it cares if it was through and exception or a return in a view.

I was under the same impression until I tried it an noticed partially committed state. In fact, state up to the error return was persisted, whereas state following the return was not. Which contradicted my experience and, I think, your sentiment as well. That’s why I raised (Haha!) this question here to get a definite and documented answer.

Interestingly, Pylon’s [pyramid-cookiecutter-alchemy example view](https://github.com/Pylons/pyramid-cookiecutter-alchemy/blob/latest/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/views/default.py) `return`s as well, instead of `raise`ing an exception.

**Comment by Natim** [comment]
> If it’s open source, mind sharing a link

https://github.com/Kinto/kinto/blob/master/kinto/core/views/errors.py

**Comment by leplatrem** [comment]
> In particular, does Cornice have a “catch all exceptions” view or should I use Pyramid’s exception context for that?

Nope it doesn't, but it could indeed!


> Interestingly, Pylon’s pyramid-cookiecutter-alchemy example view returns as well, instead of raiseing an exception.

I don't know the fundamental difference to be honest. It completely depends on your design I guess. Returning makes the final response explicitly specified in the view, whereas raising gives a sort of abstraction between the error and the way it's rendered. I personally prefer the latter since Cornice views just return dict objects (and not necessary responses objects), and because I usually want every error to be rendered the same way. But I concede it's a matter of taste.

**Comment by jenstroeger** [comment]
> @leplatrem Nope it doesn't, but it could indeed!

Should I file a feature issue?

As for `return` vs. `raise`, I’m concerned about exception performance but that might be unfounded. The important thing is to [_abort_](http://docs.sqlalchemy.org/en/latest/orm/session_api.html#sqlalchemy.orm.session.Session.rollback) the request’s DB transaction in case of an error, and I have to test that again because I don’t trust that `return` aborts correctly in the above code.

**Comment by jenstroeger** [comment]
Crumms. I just checked again, and changes to an ORM backed object are persisted even though the view function returns with a `request.errors.status` set to `4xx`. I would have expected that the error status causes the transaction to abort and the ORM backed object to stay untouched.

**Comment by leplatrem** [comment]
Yes, if you look at the docs/code of `pyramid_tm`, you'll see that the transaction is rolledback only on `5XX` responses. You can customize that there

**Comment by jenstroeger** [comment]
Thanks, @leplatrem, using a [commit-veto hook](https://docs.pylonsproject.org/projects/pyramid_tm/en/latest/#adding-a-commit-veto-hook) worked like a charm.
