### ISSUE TITLE
Is Cornice withering away?

### ISSUE THREAD

**Issue by jenstroeger** [Cornices/cornice#457]
The [last commit](https://github.com/Cornices/cornice/commit/76b0390a333d59b0977646aacb76809c7829d3ad) was on 22 June, nearly three months ago.

What is the current status of, and the commitment to this project? Pyramid seems quite active and moving forward, and I’m rather worried that Cornice is being abandoned.

**Comment by Natim** [comment]
Cornice as any Pyramid projects move forward with collaborators using it.
Cornice is used actively in Kinto and many other projects and we have been doing lots of refactoring lately (in 2017 and since 2015), also what are three months for a so small and stable project?

Pull-Requests are being reviewed, issues are taking cared of. So far so good, thank you for wondering 👍 

Feel free to help if you feel things are missing, you are most welcome.

**Comment by Natim** [comment]
Also you might be interested in the work we have been doing in [Kinto.core](docs.kinto-storage.org/en/stable/core/index.html) (notably adding a permission, storage and cache backend to cornice as well as resources notions.)

**Comment by leplatrem** [comment]
I think the question is legitimate :) I like the fact that this project remains small and stable, with as little maintenance as possible.

But to be honest, I would really feel more comfortable with more maintainers/reviewers on board, so if you're interested to participate more with write access etc, let us know :)

Thanks for your interest ;)

**Comment by Natim** [comment]
> if you're interested to participate more with write access

I already added him as a collab.

**Comment by jenstroeger** [comment]
I am interested, yes.

Considering the list of open issues and feature requests I worry about the project becoming stagnant. We’re currently in a tight shipping cycle until Oct or so, but after that I plan some code maintenance on our server which would address Cornice issues (see [my open Cornice issues](https://github.com/Cornices/cornice/issues/created_by/jenstroeger)).

**Comment by leplatrem** [comment]
> I am interested, yes.

Excellent news!

#430 is a good way to start, rather small and scoped :) 

> [...] list of open issues and feature requests I worry about the project becoming stagnant. 

Globally I don't think there is any big feature missing. Most open issues are about guidance and developer experience when using the library. 

Personally, I wouldn't mind it became stagnant 😄  (if stable and compatible with pyramid latest versions of course ;))

**Comment by bowlofeggs** [comment]
There are some problems over in the cornice_sphinx project - could someone take a look at the open issues (and especially, the open pull requests?).

I help maintain Cornice in Fedora and I had to carry some of those patches to get it working. It'd be nice to get them merged and released upstream ☺

**Comment by Natim** [comment]
Let's do it !!

**Comment by leplatrem** [comment]
Apparently, every pull request was closed there. I'm closing this, please reopen another issue if you think there is something to be added
