### ISSUE TITLE
Why add 'context' in resource factory init parameters ?

### ISSUE THREAD

**Issue by olemoign** [Cornices/cornice#466]
https://github.com/Cornices/cornice/blob/ce52659174192717a09830b939eae1dceef5223d/cornice/service.py#L473

This breaks the Pyramid pattern of expecting only the request in the init() function and I don't really see the point of copying the `request.context` that will anyway be present ?

**Comment by leplatrem** [comment]
This has been here for a few years now, introduced by @mardiros in https://github.com/Cornices/cornice/pull/209

It raised some questions while we refactored the way Cornice handles ACL. You can read @wjehenddher interrogations here: 
https://github.com/Cornices/cornice/pull/456/files#r138968777

If you have a proposal, please share it! We really would like to align Cornice design with Pyramid, even if it means introducing other breaking changes.

**Comment by leplatrem** [comment]
@olemoign would you be interested in fixing this?

**Comment by olemoign** [comment]
The project I was working on with cornice has shutdown so I won't be able to. Sorry.
