### ISSUE TITLE
Support for marshmallow schemas

### ISSUE THREAD

**Issue by ergo** [Cornices/cornice#474]
If I would add support for marshmallow schemas would the project accept the PR?

**Comment by leplatrem** [comment]
Yes of course :) 

The `test_validation.py` might need some generalization, if you have some ideas please do! Otherwise some dedicated unit tests would be just fine.

Thanks!

**Comment by ergo** [comment]
Ok, I've started work on this already, https://github.com/ergo/cornice/commit/0701855056b504419de1e900eafa35b875c23c2a 

Now its time to write the tests and documentation.

**Comment by ergo** [comment]
Hi, I've added support for Marshmallow here https://github.com/Cornices/cornice/pull/475, 100% coverage,
Works on both Marshmallow 2.x (stable version) and 3.x beta branches pass too.

The only thing that is missing right now is documentation effort.

**Comment by leplatrem** [comment]
Fixed by #475
