### ISSUE TITLE
Unneeded code in `test_resource_custom_predicates`?

### ISSUE THREAD

**Issue by karantan** [Cornices/cornice#487]
I cannot find the reasoning behind this code: https://github.com/Cornices/cornice/blob/master/tests/test_resource_custom_predicates.py#L13-L16

Is this intentionally there or by mistake? Because it is not used in the tests so it is very confusing.

Should we remove it?

**Comment by leplatrem** [comment]
> Should we remove it?

Yes! 

Thanks!
