### ISSUE TITLE
Change the way documentation is generated

### ISSUE THREAD

**Issue by almet** [Cornices/cornice#67]
Currently, we're creating rst nodes to create the documentaiton. This means that we have code that's not easy to read and not easy to write. The benefit of this is that we're able to produce valid rst nods and thus that we can generate the documentation in different formats (pdf, html, latex, etc.).

However, we had been thinking with tarek about changing this in favor of a simple templating system, ala jinja.

**Comment by leplatrem** [comment]
Please reopen in https://github.com/Cornices/cornice.ext.sphinx if still relevant ;)
